---
allowedLicenses:
  - (MIT AND BSD-3-Clause)
  - (MIT AND Zlib)
  - (MIT OR CC0-1.0)
  - 0BSD
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - CC-BY-4.0
  - CC0-1.0
  - ISC
  - MIT
  - MPL-2.0
  - ODC-By-1.0
  - Python-2.0
  - UNLICENSED
excludedPackages: []
include: []
