arch: amd64
os: linux
dist: xenial
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - echo -e "machine git.overleaf.com\n  login $OVERLEAF_USER\n  password $OVERLEAF_PASSWD" > ~/.netrc
  - git submodule update --init --recursive
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-luatex texlive-xetex fonts-lmodern
install:
  - cd mjenrungrot.github.io
  - npm install
script:
  - cd src/overleaf
  - lualatex --interaction=nonstopmode --halt-on-error cv.tex
  - cd ../..
  - npm test                      # Test
  - npm run build                 # Build for pre-deploying
deploy:                           # Deploy to surge [latest branch]
  - provider: surge
    domain: mjenrungrot.surge.sh
    project: ./mjenrungrot.github.io/build
    on:
      all_branches: true
  - provider: pages               # Deploy to Github Pages [only source branch]
    strategy: git
    target_branch: master
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./mjenrungrot.github.io/build
    fqdn: mjenrungrot.com
    on:
      branch: source
