language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - cd mjenrungrot.github.io
  - npm install
script:
  - npm test                      # Test 
  - npm run build                 # Build for pre-deploying
deploy:                           # Deploy to surge [latest branch]
  - provider: surge
    skip_cleanup: true
    domain: mjenrungrot.surge.sh
    project: ./mjenrungrot.github.io/build
    on:
      all_branches: true
  - provider: pages               # Deploy to Github Pages [only source branch]
    skip-cleanup: true
    target-branch: master
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./mjenrungrot.github.io/build
    on:
      branch: source