language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - cd mjenrungrot.github.io
  - npm install
script:
  - npm test                      # Test 
  - npm run build                 # Build for pre-deploying
deploy:
  provider: surge
  skip_cleanup: true
  domain: mjenrungrot.surge.sh
  project: ./
on:
  branch: source