language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - cd mjenrungrot.github.io
  - npm install
script:
  - npm test                      # Test 
  - npm run build                 # Build for pre-deploying
# deploy:                           # Deploy to surge
#   provider: surge
#   skip_cleanup: true
#   domain: mjenrungrot.surge.sh
#   project: ./mjenrungrot.github.io/build
#   on:
#     branch: source
deploy:                           # Deploy to github pages
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  project: ./mjenrungrot.github.io/build
  on:
    branch: deployment_fix