language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd mjenrungrot.github.io      # Move to src folder
  - npm test                      # Test 
  - npm run build                 # Build for pre-deploying
deploy:
  provider: surge
  skip_cleanup: true
  domain: mjenrungrot.surge.sh
  project: ./mjenrungrot.github.io/build
on:
  branch: source