# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Main
email: mjenrungrot[at]hmc.edu
description: > # this means to ignore newlines until "baseurl:"
  A personal site for keeping interesting things.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mjenrungrot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  mjenrungrot

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Google Analytics
# google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
