// flow-typed signature: 8b74ec1cdcd2d217973c35cb455ff039
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.54/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
