name: Node.js CI
on:
  push:
    branches:
      - nextjs

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn build
      - run: yarn postbuild
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: nextjs-gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
